version: '3.1'

services:
    web:
        image: nginx:latest
        ports:
            - "5555:80"
        volumes:
            - ./src:/src
            # Je dois réécrire un peu de conf pour mon serveur
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/src
        networks:
            - code-network

    db:
        image: mariadb:10.6.4
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        networks:
            - code-network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            - PMA_ARBITRARY=1
        networks:
            - code-network

#    mongo:
#        image: mongo:4.4.6
#        restart: always
#        ports:
#            - "27017:27017"
#        # environment:
#        # MONGO_INITDB_ROOT_USERNAME: root
#        # MONGO_INITDB_ROOT_PASSWORD: example
#        networks:
#            - code-network
#
#    mongo-express:
#        image: mongo-express
#        restart: always
#        ports:
#            - "8081:8081"
#        environment:
#            # ME_CONFIG_MONGODB_ADMINUSERNAME: root
#            # ME_CONFIG_MONGODB_ADMINPASSWORD: example
#            # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#            ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
#        networks:
#            - code-network

networks:
    code-network:
        driver: bridge

